import { existsSync } from "node:fs";
import { appendFile, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const PLANNING_DIR = "docs/ai";

const README_CONTENT = `# docs/ai

Project-local planning workspace for AI agents.

## Layout

\`\`\`txt
tasks/backlog/  Draft tasks (not yet ready for implementation)
tasks/ready/    Ready-to-implement tasks (prioritized)
tasks/done/     Completed tasks (kept for reference)
plans/          Implementation plans with task manifest (see src/references/plan-template.md; fur plan status)
state.json      Machine-readable state from fur refresh
progress/       Progress snapshots (fur compact -> progress/archive/)
context/        Project context: MCP, issue tracker, verification, domain notes
\`\`\`

## Rules

- Keep secrets out of this folder.
- External tracker writes require clear \`.fur.workspace/config.json\` permission.
- Local markdown is the fallback when MCP/Jira/GitHub is unavailable.
- Prefer loading \`progress/latest.md\` in agents; do not paste full task history into chat.
- Link to task files instead of pasting their full contents.
- Archive long context digests to \`context/archive/\` with a short summary left in place.
- Use caveman-style concise responses by default unless clarity or safety requires full prose.
`;

const ISSUE_TRACKER_CONTENT = `# Issue Tracker

## Mode

local-markdown

## Supported Modes

- local-markdown: Tasks stored as markdown files in \`docs/ai/tasks/\`
- jira: Sync with Jira via MCP (requires configuration)
- github: Sync with GitHub Issues via MCP (requires configuration)
- mixed: Local markdown with selective external sync

## Rules

- External writes are allowed only when \`.fur.workspace/config.json\` selects the tracker/repo unambiguously and the relevant \`writeAllowed\` flag is true.
- Reading external issues for context is allowed when tools are available.
- If external tracker is unavailable, write local markdown task.
- Never fake an external issue ID.
`;

const MCP_CONTENT = `# MCP Context

Document available MCP sources here.

Examples:

- Jira / Atlassian
- GitHub
- Context7
- Browser / Playwright
- Figma

## Rules

- Read-only context gathering is allowed when tools are configured.
- Write actions require clear \`.fur.workspace/config.json\` permission.
- If MCP is unavailable, continue with local markdown.
`;

const VERIFICATION_CONTENT = `# Verification

Update these commands per project.

\`\`\`bash
pnpm typecheck
pnpm lint
pnpm test
\`\`\`

## Rules

- Run targeted checks first (e.g., lint only changed files).
- Do not claim done when verification fails.
- If a command is missing, explain it and suggest an alternative.
- Always run verification before marking a task as done.
`;

const CONVENTIONS_CONTENT = `# Agent Conventions

- Use Turkish for user-facing conversation unless the user asks otherwise.
- Prefer short plain-text replies; no YAML control-plane blocks at the end of messages.
- Use caveman style only when the user invokes caveman or \`responseDepth: concise\` clearly allows it.
- Superpowers skills (debug, TDD, verification) apply when the user attaches them — not by default.
- Do not add AI attribution, model names, or co-author lines to commits or PR bodies.
- Commits and PR creation require explicit user approval.
- External writes require explicit approval or clear workspace config permission.
`;

async function discoverProjectSummary(projectRoot: string): Promise<string> {
  const lines: string[] = [];
  const packagePath = join(projectRoot, "package.json");
  if (existsSync(packagePath)) {
    try {
      const pkg = JSON.parse(await readFile(packagePath, "utf-8")) as {
        name?: string;
        scripts?: Record<string, string>;
      };
      if (pkg.name) lines.push(`- Package: ${pkg.name}`);
      const scripts = Object.keys(pkg.scripts ?? {});
      if (scripts.length > 0) lines.push(`- Scripts: ${scripts.join(", ")}`);
    } catch {
      lines.push("- package.json: present but unreadable");
    }
  }

  try {
    const entries = await readdir(projectRoot, { withFileTypes: true });
    const dirs = entries
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .filter((name) => !name.startsWith(".") && name !== "node_modules")
      .sort()
      .slice(0, 12);
    if (dirs.length > 0) lines.push(`- Top-level dirs: ${dirs.join(", ")}`);
  } catch {
    lines.push("- Top-level dirs: unavailable");
  }

  return lines.length > 0 ? lines.join("\n") : "- No project metadata discovered yet.";
}

async function architectureContent(projectRoot: string): Promise<string> {
  return `# Architecture Context

Generated by \`fur init\`. Update when project structure changes.

## Discovered Signals

${await discoverProjectSummary(projectRoot)}

## Notes

- Keep durable architecture facts here.
- Link deeper docs instead of pasting long transcripts into chat.
`;
}

function agentInstructionsBlock(): string {
  return `<!-- docs-ai:start -->
## AI Context

- Durable docs: \`docs/ai/\` — see \`docs/ai/README.md\`.
- Load \`docs/ai/config.json\`, \`docs/ai/progress/latest.md\`, and \`docs/ai/context/*\` before deep work.
- Optional tasks: \`docs/ai/tasks/\`; plans: \`docs/ai/plans/\`.
- Commit and PR creation require explicit user approval.
<!-- docs-ai:end -->`;
}

async function upsertBlock(path: string, fallbackTitle: string): Promise<void> {
  const block = agentInstructionsBlock();
  if (!existsSync(path)) {
    await writeFile(path, `${fallbackTitle}\n\n${block}\n`);
    return;
  }
  const current = await readFile(path, "utf-8");
  const pattern =
    /<!-- (?:fur-docs-ai|docs-ai):start -->[\s\S]*?<!-- (?:fur-docs-ai|docs-ai):end -->/m;
  const next = pattern.test(current)
    ? current.replace(pattern, block)
    : `${current.trimEnd()}\n\n${block}\n`;
  await writeFile(path, next);
}

async function writeAgentRedirects(projectRoot: string): Promise<void> {
  await upsertBlock(join(projectRoot, "AGENTS.md"), "# Agent Instructions");
  const claudePath = join(projectRoot, "CLAUDE.md");
  const redirect = `# Claude Instructions

Read \`AGENTS.md\`.
`;
  await writeFile(claudePath, `${redirect}\n`);
}

export function planningDir(projectRoot: string): string {
  return join(projectRoot, PLANNING_DIR);
}

export async function ensurePlanningDirs(projectRoot: string): Promise<void> {
  const base = planningDir(projectRoot);
  await mkdir(join(base, "tasks", "backlog"), { recursive: true });
  await mkdir(join(base, "tasks", "ready"), { recursive: true });
  await mkdir(join(base, "tasks", "done"), { recursive: true });
  await mkdir(join(base, "plans"), { recursive: true });
  await mkdir(join(base, "progress"), { recursive: true });
  await mkdir(join(base, "progress", "archive"), { recursive: true });
  await mkdir(join(base, "context"), { recursive: true });
  await mkdir(join(base, "context", "archive"), { recursive: true });
}

export async function writePlanningFiles(projectRoot: string): Promise<void> {
  const base = planningDir(projectRoot);
  await writeFile(join(base, "README.md"), README_CONTENT);

  const issuePath = join(base, "context", "issue-tracker.md");
  if (!existsSync(issuePath)) {
    await writeFile(issuePath, ISSUE_TRACKER_CONTENT);
  }

  const mcpPath = join(base, "context", "mcp.md");
  if (!existsSync(mcpPath)) {
    await writeFile(mcpPath, MCP_CONTENT);
  }

  const verificationPath = join(base, "context", "verification.md");
  if (!existsSync(verificationPath)) {
    await writeFile(verificationPath, VERIFICATION_CONTENT);
  }

  await writeFile(join(base, "context", "architecture.md"), await architectureContent(projectRoot));

  const conventionsPath = join(base, "context", "conventions.md");
  if (!existsSync(conventionsPath)) {
    await writeFile(conventionsPath, CONVENTIONS_CONTENT);
  }

  await writeAgentRedirects(projectRoot);
}

export async function addGitignoreEntry(projectRoot: string): Promise<void> {
  const gitignoreFile = join(projectRoot, ".gitignore");
  let content = "";
  if (existsSync(gitignoreFile)) {
    content = await readFile(gitignoreFile, "utf-8");
  }
  if (!content.split("\n").some((line) => line.trim() === `${PLANNING_DIR}/`)) {
    await appendFile(
      gitignoreFile,
      `\n# Agent context workspace\n${PLANNING_DIR}/\n`,
    );
  }
}

export interface PlanningConfig {
  gitignore: boolean;
  questionLevel: string;
  projectMaturity: string;
  responseDepth: string;
  evidenceStyle: string;
  verificationStrictness: string;
  automationMode: string;
}

export async function writeConfig(
  projectRoot: string,
  config: PlanningConfig,
): Promise<void> {
  const createdAt = new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
  const body = {
    version: 2,
    planningDir: PLANNING_DIR,
    gitignore: config.gitignore,
    localTaskMode: "local-markdown",
    questionLevel: config.questionLevel,
    projectMaturity: config.projectMaturity,
    responseDepth: config.responseDepth,
    evidenceStyle: config.evidenceStyle,
    verificationStrictness: config.verificationStrictness,
    automationMode: config.automationMode,
    planning: {
      planLock: "enabled",
    },
    questionPolicy: {
      askBeforeSplittingLargeTasks: true,
      askWhenAcceptanceCriteriaMissing: true,
      askWhenTrackerConfigAmbiguous: true,
      askWhenRiskIsHigh: true,
    },
    createdAt,
  };
  await writeFile(
    join(planningDir(projectRoot), "config.json"),
    `${JSON.stringify(body, null, 2)}\n`,
  );
}

export async function countMd(dir: string): Promise<number> {
  if (!existsSync(dir)) return 0;
  const glob = new Bun.Glob("*.md");
  let count = 0;
  for await (const _ of glob.scan({ cwd: dir, onlyFiles: true })) {
    count++;
  }
  return count;
}
